---
title: "Travelling with Angular"
author: "Doyin"
date: "September 21, 2018"
output: html_document
---

Eloquent Laravel (Build a cutting edge App with Laravel 5.7) Building a Cinema Booking System
Practical PostgreSQL for Laravel Developers (Build a cutting edge App with Laravel 5.7) Building as Hotel Reservation Site System
Practical MongoDB for Laravel Developers (Build a cutting edge App with Laravel 5.7) Building an Online Learning Platform 
MongoDB Recipes for Fullstack Developers (Solving Tommorrows Problem Today)
Mind Taming for Software Developers
The Reciprocity Law for Software Developers
Freelancer Cookbook
Laravel Visa

**The Innocent Challenger** Challenger to Exploring the Next Galaxy by Twin Brother Vincyl

**A Pinhole in the Mind** Extrapolating the Natural Talents within you. How could he be helped. Sees and heard aliens everytime

**I Missed the Sunrise (Exploring the Rudtelege Planet)**

A lone stranger that inadvertently sends back a message to himself through a mirage from another planet. How did he get there in the first place?. A Fictitious Book on how a lonely developer woked up to find himself in a strange land filled with mind blowing fantasies. He got so wrapped up in his mind, but then he was the only one ever to walk the planet. Yet the environment and advanced tech of the planet supplied him with everything he could ever wished for. High towing buildings with trains passing and connecting buildings. Still stange feelings were scent of fresh vegetations, countless birds rythmingly singing with systemic patterns. The sad event? he couldn't see them. He tried as much as possible echoing through the dark forest of Jugunxy. Yet still found himself alone. What could have gone wrong? Was his mind playing tricks on him? Was he captured by aliens? Did he creat or carved out his own universe? was he in a parallel universe or could it a dream?...Find out in this adventurous book I missed the sunrise.

A virtually technology had been used on him to be enstranged in the forever land. He was however programmed with a very low probability value to figure out only if he could develop self-intelligenece within the virtual environment. A mad programmer secretly carried out a research on virtual environemnt but failed to profer a standard routine to recapturing him back. 

No reflection, no memories of past life. He could only sees reflections of buildings and other things around him and never himself. 

**The Channel**

A black hole inadvertently discoverd by a scientist in meeting the aliens. Only Three exists in the world.  The first scientist to discover the blackhole got empowered, brought new changes to the world but in a secret agreement with........?
